######################################################################
# Automatically generated by qmake (2.01a) ?? 2? 20 20:50:06 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . \
              libjpeg_arm/include \
              libmysql_arm/include/mysql \
INCLUDEPATH += . libjpeg_arm/include 

# Input
HEADERS += common.h \
           jpeg_util.h \
           logindialog.h \
           memory_pool.h \
           pthreadbalance.h \
           pthreadvideocapture.h \
           pthreadvideoclassify.h \
           video_util.h \
           widget.h \
           libjpeg_arm/include/jconfig.h \
           libjpeg_arm/include/jerror.h \
           libjpeg_arm/include/jmorecfg.h \
           libjpeg_arm/include/jpeglib.h \
           libmysql_arm/include/mysql/decimal.h \
           libmysql_arm/include/mysql/errmsg.h \
           libmysql_arm/include/mysql/keycache.h \
           libmysql_arm/include/mysql/m_ctype.h \
           libmysql_arm/include/mysql/m_string.h \
           libmysql_arm/include/mysql/my_alloc.h \
           libmysql_arm/include/mysql/my_attribute.h \
           libmysql_arm/include/mysql/my_compiler.h \
           libmysql_arm/include/mysql/my_config.h \
           libmysql_arm/include/mysql/my_dbug.h \
           libmysql_arm/include/mysql/my_dir.h \
           libmysql_arm/include/mysql/my_getopt.h \
           libmysql_arm/include/mysql/my_global.h \
           libmysql_arm/include/mysql/my_list.h \
           libmysql_arm/include/mysql/my_net.h \
           libmysql_arm/include/mysql/my_no_pthread.h \
           libmysql_arm/include/mysql/my_pthread.h \
           libmysql_arm/include/mysql/my_sys.h \
           libmysql_arm/include/mysql/my_xml.h \
           libmysql_arm/include/mysql/mysql.h \
           libmysql_arm/include/mysql/mysql_com.h \
           libmysql_arm/include/mysql/mysql_embed.h \
           libmysql_arm/include/mysql/mysql_time.h \
           libmysql_arm/include/mysql/mysql_version.h \
           libmysql_arm/include/mysql/mysqld_ername.h \
           libmysql_arm/include/mysql/mysqld_error.h \
           libmysql_arm/include/mysql/plugin.h \
           libmysql_arm/include/mysql/readline.h \
           libmysql_arm/include/mysql/sql_common.h \
           libmysql_arm/include/mysql/sql_state.h \
           libmysql_arm/include/mysql/sslopt-case.h \
           libmysql_arm/include/mysql/sslopt-longopts.h \
           libmysql_arm/include/mysql/sslopt-vars.h \
           libmysql_arm/include/mysql/typelib.h \
           /usr/include/mysql/mysql.h \
           /usr/include/mysql/mysql_version.h \
           /usr/include/mysql/mysql_com.h \
           /usr/include/mysql/binary_log_types.h \
           /usr/include/mysql/my_command.h \
           /usr/include/mysql/mysql_time.h \
           /usr/include/mysql/my_list.h \
           /usr/include/mysql/mysql/client_plugin.h \
           /usr/include/mysql/mysql/plugin_auth_common.h \
           /usr/include/mysql/typelib.h \
           /usr/include/mysql/my_alloc.h \
           /usr/include/mysql/mysql/psi/psi_memory.h \
           /usr/include/mysql/mysql/psi/psi_base.h
FORMS += logindialog.ui widget.ui
SOURCES += common.cpp \
           jpeg_util.cpp \
           logindialog.cpp \
           main.cpp \
           memory_pool.cpp \
           pthreadbalance.cpp \
           pthreadvideocapture.cpp \
           pthreadvideoclassify.cpp \
           video_util.cpp \
           widget.cpp \
